apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: abdisiamak/springboot-online-shop:tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypass
            - name: JAVA_TOOL_OPTIONS
              value: >
                -javaagent:/otel/opentelemetry-javaagent.jar
                -Dotel.traces.exporter=otlp
                -Dotel.exporter.otlp.endpoint=http://jaeger.monitoring.svc.cluster.local:4317
                -Dotel.resource.attributes=service.name=springboot-service
